### ISSUE TITLE
 Error while indexing content from /home/location

### ISSUE THREAD

**Issue by karnamonkster** [dadoonet/fsriver#102]
Hi,

Configuration: ES 1.3.7 (2 nodes)
FS River - 1.3.1
Cluster state - Green

River configuration
PUT _river/mydocs/_meta
{
  "type": "fs",
  "fs": {
    "url": "/home/location",
    "update_rate": "1h",
    "includes": [ "*.doc" , "*.xls", "*.pdf" ]
  },
  "index": {
    "index": "docs",
    "type": "doc",
    "bulk_size": 50
  }
}

The river gets created and the index uses the default mapping.
Error in logs:

[2015-02-13 12:44:07,689][WARN ][fr.pilato.elasticsearch.river.fs.river.FsRiver] [ES-Node] [fs][mydocs] Error while indexing content from /home/location/Documents
[2015-02-13 12:59:07,692][WARN ][fr.pilato.elasticsearch.river.fs.river.FsRiver] [ES-Node] [fs][mydocs] Error while indexing content from /home/location/Documents

Anything i am missing?
I tried restarting the nodes.
Nothing in the index "docs"
![image](https://cloud.githubusercontent.com/assets/5524898/6183962/eb950018-b381-11e4-9c24-d7ea1bcb56b7.png)

**Comment by dadoonet** [comment]
What gives ls -l /home/location/
Wondering if elasticsearch user can read /home/location/Documents

**Comment by karnamonkster** [comment]
Here is the output

$ ls -l /home/$USER/Documents/
total 164680
-rw-r-----  1 $USER egi   305393 Dec 19 12:01 9711996913.pdf
-rw-r--r--  1 $USER egi   188416 Oct 20 12:02 Access Management.doc
drwxr-xr-x  2 $USER egi     4096 Dec  2 14:35 Assessments
-rw-r-----  1 $USER egi   385346 Dec 15 22:04 billnov.pdf
-rw-r-----  1 $USER egi 47187964 Dec 14 02:53 CanadaJobs-Booklet-8-pages-2-sept-printable.pdf
-rw-r--r--  1 $USER egi     4493 Jul 11  2014 chatwithtomas
drwx------  8 $USER egi     4096 Aug 13  2014 cis-cat-full
-rw-------  1 $USER egi  2380103 Jul 23  2014 CIS_CentOS_Linux_6_Benchmark_v1.0.0.pdf
drwx------  3 $USER egi     4096 Aug 13  2014 CIS_CentOS_Linux_6_Benchmark_v1.0.0_Remediation_Kit
-rw-r--r--  1 $USER egi  6039465 Aug  2  2014 CISM Review Manual 2013.pdf
-rw-r-----  1 $USER egi   336085 Nov 24 14:35 computer_hacking_forensic_investigator.pdf
-rw-r--r--  1 $USER egi    13094 Jan  8 12:55 CONTACT FRAMEWORK 2015 - T&Q.xlsx
drwxr-xr-x  2 $USER egi     4096 Dec 23 17:56 csv
-rw-r--r--  1 $USER egi   714919 Dec 11 14:24 Daily DC OPS SLA Live Doc Ver 1.1 - 12.09.2014.xlsx

**Comment by dadoonet** [comment]
I meant ls -l /home/$USER

**Comment by karnamonkster** [comment]
Here it is.

drwxr-xr-x  3 $USER egi     4096 Dec 18 17:09 AnypointStudio
drwxr-xr-x  3 $USER egi     4096 Jul  4  2014 Application Data
-rw-r--r--  1 $USER egi    81618 Jun 25  2014 Bookmarks
drwxr-xr-x  4 $USER egi     4096 Sep  2 12:38 CIS-CAT_Results
-rw-r--r--  1 $USER egi     4575 Jan  7 14:29 cupsd.conf
drwxr-xr-x 12 $USER egi     4096 Feb 13 11:43 Desktop
drwx------ 37 $USER egi     4096 Feb 13 11:17 Documents
drwxr-xr-x 20 $USER egi    36864 Feb 13 12:28 Downloads
-rw-r--r--  1 $USER egi     8980 Jun 27  2014 examples.desktop
drwxr-xr-x  3 $USER egi     4096 Sep 30 11:35 FF32
drwx------  3 $USER egi     4096 Jun 27  2014 firefoxback
-rw-r--r--  1 $USER egi    40676 Feb 12 19:51 hs_err_pid23820.log
-rw-r--r--  1 $USER egi    97433 Nov 28 02:17 hs_err_pid24722.log

**Comment by karnamonkster** [comment]
Well it worked .. chose a different location and viola!! 
I am all set... Thanks

**Comment by dadoonet** [comment]
Yeah. I think you are running elasticsearch from another user than `$USER`. `Documents` is not readable for this user: `drwx------`
