### ISSUE TITLE
Deprecate river

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/fsriver#109]
Rivers will be deprecated.
I'm currently working on porting part of the code to [logstash](https://www.elastic.co/products/logstash).

**Comment by mishatatinets** [comment]
That is sad

**Comment by cmrichards** [comment]
What specific feature has elasticsearch deprecated that will stop this form working? It thought elastic search could index any data you sent it?

**Comment by dadoonet** [comment]
River class does not exist anymore basically. So you can't run this plugin within an elasticsearch node.

Something that people could do is or now to change the FSRiver class to become a `main()` application so anyone could run it from the command line.

**Comment by dadoonet** [comment]
I started a big refactoring in this branch: https://github.com/dadoonet/fsriver/tree/big-refactor

Things seems to work fine for now... Stay tuned...

Closing.
