### ISSUE TITLE
SSH connection doesn't get closed

### ISSUE THREAD

**Issue by Kandru** [dadoonet/fsriver#96]
I've got a problem and hopefully I don't missed any other information about this. Your plugin is working like expected but I noticed that it does not close the ssh sessions. After 24 hours there are more then 30 opened connections (can't summarize them on one fullHD screen). After some time our destination server will reach the process limit for that specific user and no new ssh connection could established.

I use EL version[1.3.6] and installed your plugin with the command line plugin installation tool that you prefer at the readme.

![open_ssh](https://cloud.githubusercontent.com/assets/1965552/5813571/00e9e8b2-a080-11e4-96c0-e5f4633c8947.png)
```
curl -XPUT localhost:9200/_river/fs_dokuwiki/_meta -d '
{
  "type" : "fs",
  "fs": {
    "url": "/DIRECTORY",
    "server": "HOSTNAME",
    "port": 22,
    "username": "USERNAME",
    "pem_path": "/home/USER/.ssh/id_rsa",
    "protocol": "ssh",
    "update_rate": "3h",
    "includes": "*.txt"
  }
}
'

```

Does there already exist a fix? If so would it be possible to compile me a working version for elasticsearch 1.3.6? Thanks :)

**Comment by dadoonet** [comment]
That's very true. Working on a fix.

**Comment by dadoonet** [comment]
I pushed a fix.
Before releasing, could you test this version?

```
bin/plugin -install fsriver --url https://oss.sonatype.org/content/repositories/snapshots/fr/pilato/elasticsearch/river/fsriver/1.3.2-SNAPSHOT/fsriver-1.3.2-20150120.134740-1.zip
```

Thanks for your help!

**Comment by Kandru** [comment]
Hey dadoonet,

thanks for the fast work! Great! I just updated your elasticsearch plugin and will wait until tomorrow - update indices will need some time.

**Comment by Kandru** [comment]
Okay seems not to work properly. Got only 2 connections yesterday after restart. Now I have much more currently opened connections. They simply do not close. No more "FIN_WAIT2" or "TIME_WAIT" only "CONNECTED" ("Verbunden").
![open_ssh](https://cloud.githubusercontent.com/assets/1965552/5851933/da23ff98-a20e-11e4-8f88-cd0dbb67baa7.png)

**Comment by Kandru** [comment]
Hey @dadoonet need to restart our elasticsearch once a day, otherwise our remote server won't work properly (no more ssh connections allowed). Any progress on this?

**Comment by Kandru** [comment]
Hey @dadoonet created a pull request: https://github.com/dadoonet/fsriver/pull/104
